baseurl = "./"
title = "OpenPitrix"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
copyright = "Openpitrix Technology © 2018"

[languages]
[languages.en]
    languageCode = "en-us"
    footer = "&copy; [openpitrix.io](https://openpitrix.io) 2017 | [Github](https://github.com/openpitrix) | [Gitee](https://gitee.com/openpitrix)"

    [[languages.en.menu.main]]
        name = "Documents"
        url = "/en/#"
        weight = 1
    [[languages.en.menu.main]]
        name = "Features"
        url = "/en/#third"
        weight = 2
    [[languages.en.menu.main]]
        name = "Use Cases"
        url = "/en/#eighth"
        weight = 3
    [[languages.en.menu.main]]
        name = "About"
        url = "/en/#about"
        weight = 4

    [languages.en.index.first]
        title = "Application Management"
        subtitle = "Platform on Multi-Cloud Environment"
        desc = "OpenPitrix is an Open-source, enterprise  system for  package ,deploy and orchestration applications into multiple cloud environments such as QingCloud, AWS, Kubernetes etc."
        link = "COMING SOON…"
    [languages.en.index.second]
        title = "Why OpenPitrix?"
        desc_begin = "Since software used in business, diversity software was developed. For example, categorize by architecture："
        desc_end = "This is Cloud era, so all above application must run on cloud computing, Just like QingCloud,AWS, Or VMware, Kubernetes based envrionment. Which framework or platform can do this? So OpenPitrix make sence, born for resovle this problem."
        [[languages.en.index.second.architecture]]
            name = "Java EE traditional enterprise application."
            weight = 1
        [[languages.en.index.second.architecture]]
            name = "LAMP ( linux,apache,mysql/postgresql,php/python/perl ) Open Source Software stack."
            weight = 2
        [[languages.en.index.second.architecture]]
            name = "Virtalization image."
            weight = 3
        [[languages.en.index.second.architecture]]
            name = "Container image."
            weight = 4        
        [[languages.en.index.second.architecture]]
            name = "Microservice components."
            weight = 5
        [[languages.en.index.second.architecture]]
            name = "and a lot of more."
            weight = 6
    [languages.en.index.third]
        title = "Template application and deployment framework"
        desc = "Significantly reduce learning costs and operational complexity through declarative template specifications, reducing development cycles from months to days or even hours, dramatically reducing cloud application development, deployment and operational complexity."
    [languages.en.index.fourth]
        title = "Support multiple cloud platforms"
        desc_begin = "Adopted plug-in style development framework, abstraction the current mainstream cloud platform interface , uniform them for the user is completely transparent, reducing complexity for application developer."
        desc_end = "public cloud platform supported include: AWS, GCE, Azure, QingCloud,etc.\r\nprivate cloud platform supported : Kubernetes, OpenStack, QingCloud,etc. "
    [languages.en.index.fifth]
        title = "Unify all kind of application,monolitic,microservice,distributed,etc."
        desc = "The technology is evolving, application is same, but old sytle not disappear. all kinds of application coexist in cloud computing era. OpenPitrix adopted distributed configurtion management, abstract meta configuration infomation, compatible with all(almost) application."
    [languages.en.index.sixth]
        title = "Adopted microservice for openpitrix itself"
        desc = "Openpitrix adopted microservice, every funcation have indepent service, architecture high level."
    [languages.en.index.seventh]
        title = "As the picture show"
    [languages.en.index.eighth]
        title = "Use Cases"        
    [languages.en.index.footer]
        title = "About Pitrix itself"
        desc = "Pitrix [‘paitriks]means the matrix of PaaS and IaaS which makes it easy to develop, deploy, manage applications including PaaS on various runtime environments, i.e., Pitrix = PaaS + IaaS + Matrix. It also means a matrix that contains endless (PI - the Greek letter “π”) applications."  

[languages.zh]
    languageCode = "zh-cn"
    footer = "&copy; [openpitrix.io](https://openpitrix.io) 2017 | [Github](https://github.com/openpitrix) | [码云](https://gitee.com/openpitrix)"
    
    [[languages.zh.menu.main]]
        name = "文档"
        url = "/zh/#"
        weight = 1
    [[languages.zh.menu.main]]
        name = "特性"
        #url = "/zh/features"
        url = "/zh/#third"
        weight = 2
    [[languages.zh.menu.main]]
        name = "案例"
        #url = "/zh/cases"
        url = "/zh/#eighth"
        weight = 3
    [[languages.zh.menu.main]]
        name = "关于"
        url = "/zh/about"
        weight = 4

    [languages.zh.index.first]
        title = "Application Management"
        subTitle = "Platform on Multi-Cloud Environment"
        desc = "OpenPitrix is an Open-source, enterprise  system for  package ,deploy and orchestration applications into multiple cloud environments such as QingCloud, AWS, Kubernetes etc."
        link = "敬请期待..."
    [languages.zh.index.second]
        title = "Why OpenPitrix?"
        desc_begin = "Since software used in business, diversity software was developed. For example, categorize by architecture："
        desc_end = "This is Cloud era, so all above application must run on cloud computing, Just like QingCloud,AWS, Or VMware, Kubernetes based envrionment. Which framework or platform can do this? So OpenPitrix make sence, born for resovle this problem."
        [[languages.zh.index.second.architecture]]
            name = "Java EE traditional enterprise application."
            weight = 1
        [[languages.zh.index.second.architecture]]
            name = "LAMP ( linux,apache,mysql/postgresql,php/python/perl ) Open Source Software stack."
            weight = 2
        [[languages.zh.index.second.architecture]]
            name = "Virtalization image."
            weight = 3
        [[languages.zh.index.second.architecture]]
            name = "Container image."
            weight = 4        
        [[languages.zh.index.second.architecture]]
            name = "Microservice components."
            weight = 5
        [[languages.zh.index.second.architecture]]
            name = "and a lot of more."
            weight = 6        
    [languages.zh.index.third]
        title = "Template application and deployment framework"
        desc = "Significantly reduce learning costs and operational complexity through declarative template specifications, reducing development cycles from months to days or even hours, dramatically reducing cloud application development, deployment and operational complexity."
    [languages.zh.index.fourth]
        title = "Support multiple cloud platforms"
        desc_begin = "Adopted plug-in style development framework, abstraction the current mainstream cloud platform interface , uniform them for the user is completely transparent, reducing complexity for application developer."
        desc_end = "public cloud platform supported include: AWS, GCE, Azure, QingCloud,etc.\r\nprivate cloud platform supported : Kubernetes, OpenStack, QingCloud,etc. "
    [languages.zh.index.fifth]
        title = "Unify all kind of application,monolitic,microservice,distributed,etc."
        desc = "The technology is evolving, application is same, but old sytle not disappear. all kinds of application coexist in cloud computing era. OpenPitrix adopted distributed configurtion management, abstract meta configuration infomation, compatible with all(almost) application."
    [languages.zh.index.sixth]
        title = "Adopted microservice for openpitrix itself"
        desc = "Openpitrix adopted microservice, every funcation have indepent service, architecture high level."
    [languages.zh.index.seventh]
        title = "As the picture show"
    [languages.zh.index.eighth]
        title = "Use Cases"        
    [languages.zh.index.footer]
        title = "About Pitrix itself"
        desc = "Pitrix [‘paitriks]means the matrix of PaaS and IaaS which makes it easy to develop, deploy, manage applications including PaaS on various runtime environments, i.e., Pitrix = PaaS + IaaS + Matrix. It also means a matrix that contains endless (PI - the Greek letter “π”) applications."        

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
[params]
    description = "A website built through Hugo and blogdown."

